"use client";

/**
 * /r/[reportId] — public, read-only shared report (V15b).
 *
 * Renders any archived report without a login by fetching the uuid4 capability
 * URL (GET /api/reports/{id}, which V9 deliberately kept open). Reuses
 * FinalReportView WITHOUT a reportId, so the report chat stays hidden — a viewer
 * can read and Export-PDF, but not chat or edit. Client component so the fetch
 * runs in the browser (hits the host-published backend), and useParams reads the
 * dynamic segment.
 */

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { getReport } from "@/lib/api";
import type { ReportDetail } from "@/lib/types";
import { FinalReportView } from "@/components/FinalReportView";

export default function SharedReportPage() {
  const { reportId } = useParams<{ reportId: string }>();
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [detail, setDetail] = useState<ReportDetail | null>(null);

  useEffect(() => {
    if (!reportId) return;
    let active = true;
    getReport(reportId)
      .then((d) => {
        if (!active) return;
        setDetail(d);
        setState("ready");
      })
      .catch(() => active && setState("error"));
    return () => {
      active = false;
    };
  }, [reportId]);

  return (
    <main className="min-h-screen bg-backdrop text-ink">
      <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-10">
        <header className="mb-6">
          <p className="text-xs font-semibold uppercase tracking-[0.12em] text-faint">
            PortfolioPilot · shared report
          </p>
          {state === "ready" && detail && (
            <h1 className="mt-1 font-serif text-2xl font-medium tracking-[-0.02em] sm:text-3xl">
              Portfolio report
              <span className="ml-2 font-sans text-sm font-normal text-faint">
                {new Date(detail.generated_at).toLocaleString()}
              </span>
            </h1>
          )}
        </header>

        {state === "loading" && (
          <p className="mt-8 text-sm text-muted">Loading report…</p>
        )}
        {state === "error" && (
          <p className="mt-8 rounded-[4px] border border-dashed border-line px-4 py-10 text-center text-sm text-muted">
            This report isn&apos;t available.
          </p>
        )}
        {state === "ready" && detail && (
          // No reportId / diff / advice -> read-only, no chat (V15b).
          <FinalReportView report={detail.report} />
        )}

        <footer className="no-print mt-10 border-t border-line pt-4 text-xs text-faint">
          Generated by{" "}
          <Link href="/login" className="text-muted hover:text-ink">
            PortfolioPilot
          </Link>{" "}
          · educational, not financial advice.
        </footer>
      </div>
    </main>
  );
}
