"""
ORM models for PortfolioPilot.

V2: User and Portfolio (this file).
V5: Report (historical persisted reports).
V7: User.telegram_chat_id (set by the Telegram connect flow) + DeliveryPreference
    (per-user scheduled-delivery settings).

The langgraph.store.postgres tables for semantic memory (V5) are not
declared here — they are auto-managed by store.setup() and live
outside this Base.metadata namespace by design.
"""

from datetime import time

from sqlalchemy import Column, String, Integer, Float, DateTime, ForeignKey, Boolean, Time
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.base import Base


class User(Base):
    """One row per portfolio owner.

    Primary key is a string (e.g. "idan_demo") rather than autoincrement
    int — keeps user_ids stable, human-readable, and URL-safe.
    Real auth (V8) layers on top of this
    """

    __tablename__ = "users"

    id = Column(String, primary_key=True)
    name = Column(String, nullable=True)
    email = Column(String, nullable=True)
    telegram_chat_id = Column(String, nullable=True)
    # Telegram chat to deliver to; set by the V7 connect flow. Null until linked.
    hashed_password = Column(String, nullable=True)
    # bcrypt hash for credential login (V8). Null = this user can't log in
    # with a password (e.g. rows created before auth, or seeded portfolios).
    risk_profile = Column(
        String, nullable=False
    )  # "conservative" | "balanced" | "aggressive"

    # Timestamps come from Postgres (func.now()), not Python.
    # Two benefits over datetime.utcnow as a Python-side default:
    #   1. Avoids the Python 3.12 datetime.utcnow() DeprecationWarning.
    #   2. Timestamps are consistent regardless of which app server
    #      inserts the row — the DB is the single clock.
    # timezone=True stores as TIMESTAMPTZ, the correct Postgres default.
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # uselist=False makes this a scalar (1-to-1), not a list (1-to-many).
    # Each user has exactly one portfolio row in V2.
    portfolio = relationship(
        "Portfolio",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )
    # 1:1 with DeliveryPreference (V7), same shape as portfolio above.
    delivery_preference = relationship(
        "DeliveryPreference",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )


class Portfolio(Base):
    """One row per user holding their full asset map.

    The `assets` column is JSONB rather than a normalized holdings
    table for three reasons:
      1. Read pattern: always fetched as a unit ("give me this user's
         whole portfolio"). We never query "find all users holding AAPL".
      2. Shape match: the dict on disk has the exact same structure as
         what the graph receives — no transformation layer needed.
      3. Symbol set is open and heterogeneous (stocks + crypto +
         possibly TASE later). A normalized table would either lose
         that flexibility or need a discriminator column.

    If a "find users holding X" query is ever needed, Postgres supports
    JSONB containment ops (`assets ? 'AAPL'`) and GIN indexes. No
    structural change required.
    """

    __tablename__ = "portfolios"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # unique=True enforces the 1-to-1 with users at the DB level —
    # ON CONFLICT (user_id) DO UPDATE is then a valid upsert. Without
    # unique, the upsert in api/portfolio.py would have to do a
    # SELECT-then-INSERT-or-UPDATE dance with a race window.
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )

    assets = Column(JSONB, nullable=False)
    # Example: {"AAPL": 10.0, "TEVA.TA": 25.0, "BTC": 0.5}

    # Optional per-symbol buy price (cost basis) for gain/loss tracking (V20),
    # in the symbol's NATIVE currency (USD, or ILS for TASE). {symbol: buy_price}.
    # Empty = no cost basis tracked; additive + backward-compatible.
    cost_basis = Column(JSONB, nullable=False, default=dict, server_default="{}")

    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    user = relationship("User", back_populates="portfolio")


class Report(Base):
    """One persisted report, for history and transparency (V5).

    Persisted at the API boundary (in the generate handler), NOT in a graph
    node — report history is a UI concern, distinct from the graph's own
    semantic memory in the PostgresStore. Pattern #7 (DB I/O at the boundary)
    holds: the graph stays unaware that reports are archived.

    id:
        A string UUID generated by the handler (step 7), not a server-side
        autoincrement. V6 reuses this same id as the LangGraph checkpointer's
        thread_id, so the report and its resumable run share one identifier —
        which means the handler must create the id before the run starts.

    raw_result:
        The full FinalReport as JSONB — the exact payload the report_complete
        SSE event carries. /api/reports/{id} can replay a past report verbatim
        from this, with no graph re-run and no LLM cost.

    confidence_flag:
        A coarse "high" | "low" label set at persist time from the report's
        confidence (V5) or by the guardrail (V6). Nullable.
    """

    __tablename__ = "reports"

    id = Column(
        String, primary_key=True
    )  # uuid4 from the handler; reused as V6 thread_id
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,  # /api/reports/history/{user_id} filters on this
    )
    generated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    raw_result = Column(JSONB, nullable=False)
    confidence_flag = Column(String, nullable=True)  # "high" | "low" | None


class DeliveryPreference(Base):
    """One row per user: how and when scheduled reports are delivered (V7).

    1:1 with User (like Portfolio) and deliberately a SEPARATE table rather
    than columns bolted onto User — delivery is an opt-in concern with its own
    lifecycle, and isolating it keeps the User row about identity, not
    notification plumbing. The unique FK enforces the 1:1 at the DB level
    exactly as Portfolio does, so a per-user upsert is unambiguous.

    The cadence shape — why three fields for one schedule:
        `cadence` selects the rule; `interval_days` and `weekday` are the
        parameters that rule needs, and only one is ever relevant at a time:
          - "daily"        -> neither (send every day at send_time_local).
          - "every_n_days" -> interval_days (e.g. 3 = every third day).
          - "weekly"       -> weekday (0=Mon .. 6=Sun).
        Both parameter columns are nullable because each is dead weight for two
        of the three cadences. The Pydantic boundary (step 2) enforces "the
        field your cadence needs is present"; the DB just stores it. No DB CHECK
        constraints — the boundary is the source of truth (pattern #5).

    Why send_time_local (a naive TIME) + a separate IANA `timezone` string, and
    NOT one timestamptz: the user's intent is a WALL-CLOCK time, not an instant.
    08:00 in Asia/Jerusalem is a different UTC moment in winter (UTC+2) than in
    summer (UTC+3) — Israel observes DST. Freezing a UTC offset would drift an
    hour twice a year. Storing the wall-clock time and the zone NAME separately
    lets the dispatcher (V7c) resolve "the next 08:00 in this zone" with
    zoneinfo at read time, always correct across DST.

    last_sent_at is the heartbeat: the due-check (V7c) is "is now past this
    user's scheduled time for the current period, AND last_sent_at is before
    that scheduled instant?" Stamping it only AFTER a successful dispatch is
    what makes a ~10-minute cron idempotent — it won't re-send within the same
    period. Nullable because a brand-new preference has never sent.
    """

    __tablename__ = "delivery_preferences"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # unique=True -> the 1:1 with users, and an unambiguous upsert target
    # (same rationale as Portfolio.user_id).
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )

    # ─── Channels (at least one true; enforced at the Pydantic boundary) ───
    deliver_telegram = Column(Boolean, nullable=False, default=False)
    deliver_email = Column(Boolean, nullable=False, default=False)

    # ─── Schedule ───
    # String, not a DB enum — matches User.risk_profile; the Literal is
    # enforced in Pydantic.
    cadence = Column(String, nullable=False, default="daily")
    interval_days = Column(Integer, nullable=True)  # iff cadence == every_n_days
    weekday = Column(Integer, nullable=True)  # 0=Mon..6=Sun; iff cadence == weekly

    # Naive wall-clock time, paired with `timezone` below. NOT timestamptz.
    send_time_local = Column(Time, nullable=False, default=time(8, 0))
    # IANA name (e.g. "Asia/Jerusalem"). A per-user default for the demo —
    # configurable, NOT a hardcode in the scheduling logic.
    timezone = Column(String, nullable=False, default="Asia/Jerusalem")

    enabled = Column(Boolean, nullable=False, default=True)  # master on/off

    # Drives the due-check + dedupe (stamped after a successful send).
    last_sent_at = Column(DateTime(timezone=True), nullable=True)

    # ─── Threshold alerts (V18) ───
    # Condition-based pushes, evaluated frequently on the SAME scheduler tick as
    # the digest but as a cheap, deterministic, no-LLM market-data check — never
    # a graph run. Off by default; alerts_enabled is the master switch (separate
    # from `enabled`, which governs the scheduled digest) so a user can pause all
    # alerts without losing their thresholds. Each rule is opt-in via its own
    # threshold column: NULL = that rule is off.
    alerts_enabled = Column(Boolean, nullable=False, default=False)
    alert_price_move_pct = Column(Float, nullable=True)  # any holding's |24h move| >= this
    alert_portfolio_move_pct = Column(Float, nullable=True)  # whole-portfolio |24h move| >= this
    alert_concentration_pct = Column(Float, nullable=True)  # any holding's weight >= this
    # A fired rule won't re-fire until this many hours pass, so a ~10-minute tick
    # can never spam the same condition.
    alert_cooldown_hours = Column(Integer, nullable=False, default=12)
    # Per-rule dedupe heartbeat: {"<rule-key>": "<iso ts of last fire>"}. Mutated
    # by the evaluator only (never by the prefs API). New rows start empty.
    alert_state = Column(JSONB, nullable=False, default=dict, server_default="{}")

    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    user = relationship("User", back_populates="delivery_preference")
