"""
Output contract for the PortfolioPilot graph.

The FinalReport schema is the target structure every run of the graph
produces. It is passed to the synthesizer LLM via `.with_structured_output()`,
which guarantees the response matches this shape at sampling time.

Field descriptions matter: they are injected into the LLM prompt as part
of the JSON schema and directly steer the model's output. Treat them as
prompt engineering, not documentation.
"""

from typing import List, Literal
from pydantic import BaseModel, Field


class MarketInsight(BaseModel):
    """One asset's market sentiment summary.

    In V1: generated by the synthesizer from prior knowledge.
    From V3 onward: produced by a dedicated sentiment_agent per asset,
    grounded in Tavily news search results.
    """

    asset: str = Field(
        description="The asset ticker symbol, e.g. 'AAPL' for Apple or 'BTC' for Bitcoin."
    )
    sentiment: Literal["Positive", "Neutral", "Negative"] = Field(
        description="Overall market sentiment for this asset based on recent news and price action."
    )
    summary: str = Field(
        description="One to two sentence rationale grounded in concrete signals (news headlines, price movement). Avoid generic language."
    )


class RebalancingRecommendation(BaseModel):
    """A single suggested change to the user's portfolio."""

    action: Literal["reduce", "increase", "hold"] = Field(
        description="The directional change recommended for this asset."
    )
    asset: str = Field(description="The asset ticker the recommendation applies to.")
    target_change_pct: float = Field(
        ge=-100,
        le=100,
        description="Recommended change as a percent of the asset's current allocation. Negative reduces, positive increases, 0 holds.",
    )
    rationale: str = Field(
        description="Concise justification tied to market data, sentiment, or the user's risk profile."
    )


class PortfolioValuation(BaseModel):
    """Aggregate valuation snapshot at report generation time."""

    total_usd: float = Field(
        description="Total portfolio value in US dollars at the time of report generation."
    )
    change_24h_percent: float = Field(
        description="Weighted change in total portfolio value over the last 24 hours, as a percent."
    )


class FinalReport(BaseModel):
    """The complete report returned by the PortfolioPilot graph.

    Stable contract across V1 through V6. Earlier versions populate
    fewer fields meaningfully (V1 has limited market_insights since
    there is only one asset and no real sentiment search yet), but
    the shape never changes.
    """

    portfolio_valuation: PortfolioValuation = Field(
        description="Current total value and 24-hour change of the user's portfolio."
    )
    market_insights: List[MarketInsight] = Field(
        description="One sentiment insight per asset in the portfolio."
    )
    rebalancing_recommendations: List[RebalancingRecommendation] = Field(
        description="Concrete suggested changes. May be an empty list if no action is warranted."
    )
    summary_narrative: str = Field(
        description="Two to three paragraph human-readable synthesis of the analysis. Plain prose, no markdown headers."
    )
    confidence: float = Field(
        ge=0,
        le=1,
        description="Self-assessed confidence in the report, 0 to 1. Low values indicate insufficient data or conflicting signals.",
    )
