"""
Output contract for the PortfolioPilot graph.

The report is produced in two layers (V10a):

    ReportBody  — the fields the synthesizer LLM fills, bound via
        `.with_structured_output(ReportBody)`. Field descriptions matter:
        they are injected into the LLM prompt as part of the JSON schema
        and directly steer the model's output. Treat them as prompt
        engineering, not documentation.

    FinalReport — ReportBody plus `portfolio_composition`, the
        value-weighted allocation. Composition is DETERMINISTIC: it is
        computed in Python by risk_agent and attached by the synthesizer
        node after the LLM call, so exact percentages never pass through
        the model. FinalReport is the shape archived to `reports.raw_result`
        and emitted on `report_complete`.

This split honors the project rule that deterministic numbers are computed
in Python and attached to the payload, never re-emitted by the LLM.
"""

from typing import List, Literal
from pydantic import BaseModel, Field


class MarketInsight(BaseModel):
    """One asset's market sentiment summary.

    In V1: generated by the synthesizer from prior knowledge.
    From V3 onward: produced by a dedicated sentiment_agent per asset,
    grounded in Tavily news search results.
    """

    asset: str = Field(
        description="The asset ticker symbol, e.g. 'AAPL' for Apple or 'BTC' for Bitcoin."
    )
    sentiment: Literal["Positive", "Neutral", "Negative"] = Field(
        description="Overall market sentiment for this asset based on recent news and price action."
    )
    summary: str = Field(
        description="One to two sentence rationale grounded in concrete signals (news headlines, price movement). Avoid generic language."
    )


class RebalancingRecommendation(BaseModel):
    """A single suggested change to the user's portfolio."""

    action: Literal["reduce", "increase", "hold"] = Field(
        description="The directional change recommended for this asset."
    )
    asset: str = Field(description="The asset ticker the recommendation applies to.")
    target_change_pct: float = Field(
        ge=-100,
        le=100,
        description="Recommended change as a percent of the asset's current allocation. Negative reduces, positive increases, 0 holds.",
    )
    rationale: str = Field(
        description="Concise justification tied to market data, sentiment, or the user's risk profile."
    )


class PortfolioValuation(BaseModel):
    """Aggregate valuation snapshot at report generation time."""

    total_usd: float = Field(
        description="Total portfolio value in US dollars at the time of report generation."
    )
    change_24h_percent: float = Field(
        description="Weighted change in total portfolio value over the last 24 hours, as a percent."
    )


class AssetAllocation(BaseModel):
    """One asset's value-weighted slice of the portfolio (V10a).

    Deterministic: derived by the synthesizer node from risk_agent's
    `composition_pct` + `total_value_usd` — never produced by the LLM. Drives
    the dashboard allocation donut.
    """

    asset: str = Field(description="The asset ticker symbol, e.g. 'AAPL'.")
    pct: float = Field(
        description="This asset's share of total portfolio value, as a percent (0-100)."
    )
    value_usd: float = Field(
        description="This asset's value in US dollars (its pct of total_usd)."
    )


class SectorAllocation(BaseModel):
    """One sector's value-weighted slice of the portfolio (V11, deterministic)."""

    sector: str = Field(description="The sector name, e.g. 'Technology'.")
    pct: float = Field(
        description="This sector's share of total portfolio value, as a percent (0-100)."
    )


class SectorConcentration(BaseModel):
    """Whole-portfolio sector concentration (V11).

    Deterministic: computed by macro_context_agent and attached by the
    synthesizer node — never produced by the LLM. Drives the report's
    concentration callout + sector breakdown bar.
    """

    sectors: List[SectorAllocation] = Field(
        default_factory=list,
        description="Value-weighted sector breakdown, largest first.",
    )
    dominant_sector: str | None = Field(
        default=None, description="The sector with the largest value share, if any."
    )
    concentration: Literal["high", "moderate", "low", "unknown"] = Field(
        default="unknown",
        description="Concentration level of the dominant sector.",
    )
    diversification_score: float = Field(
        default=0.0,
        description="0..1; higher means value is spread across more sectors.",
    )
    note: str = Field(
        default="", description="One-line human-readable summary of the concentration."
    )


class ReportBody(BaseModel):
    """The LLM-authored body of the report.

    Bound to the synthesizer via `.with_structured_output(ReportBody)`, so
    these field descriptions are the model's format instructions. The
    deterministic `portfolio_composition` is intentionally NOT here — that
    keeps allocation percentages from ever passing through the model.
    `FinalReport` adds it after the LLM call.

    The field shapes are the stable contract carried since V1; V10a only
    lifted them out of `FinalReport` into a named body.
    """

    portfolio_valuation: PortfolioValuation = Field(
        description="Current total value and 24-hour change of the user's portfolio."
    )
    market_insights: List[MarketInsight] = Field(
        description="One sentiment insight per asset in the portfolio."
    )
    rebalancing_recommendations: List[RebalancingRecommendation] = Field(
        description="Concrete suggested changes. May be an empty list if no action is warranted."
    )
    summary_narrative: str = Field(
        description="Two to three paragraph human-readable synthesis of the analysis. Plain prose, no markdown headers."
    )
    confidence: float = Field(
        ge=0,
        le=1,
        description="Self-assessed confidence in the report, 0 to 1. Low values indicate insufficient data or conflicting signals.",
    )


class FinalReport(ReportBody):
    """The complete report returned by the PortfolioPilot graph.

    `ReportBody` (LLM-authored) plus the deterministic value-weighted
    `portfolio_composition`. This is the shape archived to
    `reports.raw_result` and streamed on `report_complete`.

    `portfolio_composition` is optional with an empty-list default so reports
    archived before V10a still deserialize and render.
    """

    portfolio_composition: List[AssetAllocation] = Field(
        default_factory=list,
        description=(
            "Value-weighted allocation per asset, attached deterministically by "
            "the synthesizer node from risk_agent's composition — not LLM-emitted. "
            "Empty when no holdings could be priced."
        ),
    )
    sector_concentration: SectorConcentration | None = Field(
        default=None,
        description=(
            "Value-weighted sector concentration, attached deterministically by "
            "the synthesizer node from macro_context_agent — not LLM-emitted. None "
            "for reports archived before V11."
        ),
    )
