"""
Output contract for the PortfolioPilot graph.

The report is produced in two layers (V10a):

    ReportBody  — the fields the synthesizer LLM fills, bound via
        `.with_structured_output(ReportBody)`. Field descriptions matter:
        they are injected into the LLM prompt as part of the JSON schema
        and directly steer the model's output. Treat them as prompt
        engineering, not documentation.

    FinalReport — ReportBody plus `portfolio_composition`, the
        value-weighted allocation. Composition is DETERMINISTIC: it is
        computed in Python by risk_agent and attached by the synthesizer
        node after the LLM call, so exact percentages never pass through
        the model. FinalReport is the shape archived to `reports.raw_result`
        and emitted on `report_complete`.

This split honors the project rule that deterministic numbers are computed
in Python and attached to the payload, never re-emitted by the LLM.
"""

from typing import List, Literal
from pydantic import BaseModel, Field


class MarketInsight(BaseModel):
    """One asset's market sentiment summary.

    In V1: generated by the synthesizer from prior knowledge.
    From V3 onward: produced by a dedicated sentiment_agent per asset,
    grounded in Tavily news search results.
    """

    asset: str = Field(
        description="The asset ticker symbol, e.g. 'AAPL' for Apple or 'BTC' for Bitcoin."
    )
    sentiment: Literal["Positive", "Neutral", "Negative"] = Field(
        description="Overall market sentiment for this asset based on recent news and price action."
    )
    summary: str = Field(
        description="One to two sentence rationale grounded in concrete signals (news headlines, price movement). Avoid generic language."
    )


class RebalancingRecommendation(BaseModel):
    """A single suggested change to the user's portfolio."""

    action: Literal["reduce", "increase", "hold"] = Field(
        description="The directional change recommended for this asset."
    )
    asset: str = Field(description="The asset ticker the recommendation applies to.")
    target_change_pct: float = Field(
        ge=-100,
        le=100,
        description="Recommended change as a percent of the asset's current allocation. Negative reduces, positive increases, 0 holds.",
    )
    rationale: str = Field(
        description="Concise justification tied to market data, sentiment, or the user's risk profile."
    )


class BenchmarkChange(BaseModel):
    """One market benchmark's 24h move, for 'are you beating the market?' (V24)."""

    name: str = Field(description="Display name, e.g. 'S&P 500'.")
    symbol: str = Field(description="Ticker proxy, e.g. 'SPY'.")
    change_24h_percent: float = Field(
        description="The benchmark's percent change over the last 24 hours."
    )


class PortfolioValuation(BaseModel):
    """Aggregate valuation snapshot at report generation time."""

    total_usd: float = Field(
        description="Total portfolio value in US dollars at the time of report generation."
    )
    change_24h_percent: float = Field(
        description="Weighted change in total portfolio value over the last 24 hours, as a percent."
    )
    # Market benchmarks' 24h change (V24) — deterministic, attached by the
    # synthesizer; empty for reports archived before V24.
    benchmark_24h: List[BenchmarkChange] = Field(default_factory=list)
    # Cost-basis P/L (V20) — deterministic, attached by the synthesizer from
    # risk_agent. Optional/None for reports without buy prices (and pre-V20 ones).
    total_cost_basis_usd: float | None = Field(
        default=None,
        description="Total cost basis (USD) across holdings that have a buy price.",
    )
    total_gain_loss_usd: float | None = Field(
        default=None, description="Total unrealized gain/loss in USD (value − cost)."
    )
    total_gain_loss_pct: float | None = Field(
        default=None, description="Total unrealized gain/loss as a percent of cost."
    )


class AssetAllocation(BaseModel):
    """One asset's value-weighted slice of the portfolio (V10a).

    Deterministic: derived by the synthesizer node from risk_agent's
    `composition_pct` + `total_value_usd` — never produced by the LLM. Drives
    the dashboard allocation donut.
    """

    asset: str = Field(description="The asset ticker symbol, e.g. 'AAPL'.")
    pct: float = Field(
        description="This asset's share of total portfolio value, as a percent (0-100)."
    )
    value_usd: float = Field(
        description="This asset's value in its own currency (USD, or ILS for TASE)."
    )
    currency: str = Field(
        default="USD",
        description="Display currency for value_usd — 'USD' or 'ILS' (TASE). V16.",
    )
    # Cost-basis P/L (V20) — None unless a buy price is set for this holding.
    cost_basis_usd: float | None = Field(
        default=None, description="Total cost paid for this holding in USD (qty × buy price)."
    )
    gain_loss_usd: float | None = Field(
        default=None, description="Unrealized gain/loss for this holding in USD."
    )
    gain_loss_pct: float | None = Field(
        default=None, description="Unrealized gain/loss as a percent of the buy price."
    )


class SectorAllocation(BaseModel):
    """One sector's value-weighted slice of the portfolio (V11, deterministic)."""

    sector: str = Field(description="The sector name, e.g. 'Technology'.")
    pct: float = Field(
        description="This sector's share of total portfolio value, as a percent (0-100)."
    )


class SectorConcentration(BaseModel):
    """Whole-portfolio sector concentration (V11).

    Deterministic: computed by macro_context_agent and attached by the
    synthesizer node — never produced by the LLM. Drives the report's
    concentration callout + sector breakdown bar.
    """

    sectors: List[SectorAllocation] = Field(
        default_factory=list,
        description="Value-weighted sector breakdown, largest first.",
    )
    dominant_sector: str | None = Field(
        default=None, description="The sector with the largest value share, if any."
    )
    concentration: Literal["high", "moderate", "low", "unknown"] = Field(
        default="unknown",
        description="Concentration level of the dominant sector.",
    )
    diversification_score: float = Field(
        default=0.0,
        description="0..1; higher means value is spread across more sectors.",
    )
    note: str = Field(
        default="", description="One-line human-readable summary of the concentration."
    )


class ReportBody(BaseModel):
    """The LLM-authored body of the report.

    Bound to the synthesizer via `.with_structured_output(ReportBody)`, so
    these field descriptions are the model's format instructions. The
    deterministic `portfolio_composition` is intentionally NOT here — that
    keeps allocation percentages from ever passing through the model.
    `FinalReport` adds it after the LLM call.

    The field shapes are the stable contract carried since V1; V10a only
    lifted them out of `FinalReport` into a named body.
    """

    portfolio_valuation: PortfolioValuation = Field(
        description="Current total value and 24-hour change of the user's portfolio."
    )
    market_insights: List[MarketInsight] = Field(
        description="One sentiment insight per asset in the portfolio."
    )
    rebalancing_recommendations: List[RebalancingRecommendation] = Field(
        description="Concrete suggested changes. May be an empty list if no action is warranted."
    )
    summary_narrative: str = Field(
        description="Two to three paragraph human-readable synthesis of the analysis. Plain prose, no markdown headers."
    )
    confidence: float = Field(
        ge=0,
        le=1,
        description="Self-assessed confidence in the report, 0 to 1. Low values indicate insufficient data or conflicting signals.",
    )


class FinalReport(ReportBody):
    """The complete report returned by the PortfolioPilot graph.

    `ReportBody` (LLM-authored) plus the deterministic value-weighted
    `portfolio_composition`. This is the shape archived to
    `reports.raw_result` and streamed on `report_complete`.

    `portfolio_composition` is optional with an empty-list default so reports
    archived before V10a still deserialize and render.
    """

    portfolio_composition: List[AssetAllocation] = Field(
        default_factory=list,
        description=(
            "Value-weighted allocation per asset, attached deterministically by "
            "the synthesizer node from risk_agent's composition — not LLM-emitted. "
            "Empty when no holdings could be priced."
        ),
    )
    sector_concentration: SectorConcentration | None = Field(
        default=None,
        description=(
            "Value-weighted sector concentration, attached deterministically by "
            "the synthesizer node from macro_context_agent — not LLM-emitted. None "
            "for reports archived before V11."
        ),
    )


class SentimentFlip(BaseModel):
    """One asset's sentiment change between two consecutive reports (V12b)."""

    asset: str = Field(description="The asset whose sentiment changed.")
    previous: Literal["Positive", "Neutral", "Negative"] = Field(
        description="Sentiment in the prior report."
    )
    current: Literal["Positive", "Neutral", "Negative"] = Field(
        description="Sentiment in the new report."
    )


class ReportDiff(BaseModel):
    """What changed since the user's previous report (V12b).

    Computed deterministically at the API boundary by diffing the two archived
    report payloads — no LLM. Note: risk violations are not persisted on the
    report, so the actionable diff is over the rebalancing recommendations
    (keyed "action asset"), which are the surfaced form of those violations.
    """

    first_report: bool = Field(
        default=False, description="True when there is no prior report to compare."
    )
    valuation_delta_pct: float | None = Field(
        default=None,
        description="Percent change in total_usd vs the prior report; None if not computable.",
    )
    sentiment_flips: List[SentimentFlip] = Field(
        default_factory=list, description="Per-asset sentiment changes."
    )
    recommendations_new: List[str] = Field(
        default_factory=list,
        description="Recommendations present now but not in the prior report (e.g. 'reduce AAPL').",
    )
    recommendations_resolved: List[str] = Field(
        default_factory=list,
        description="Recommendations in the prior report but no longer present.",
    )


class GradedCall(BaseModel):
    """One prior recommendation graded against the asset's actual move (V13)."""

    asset: str = Field(description="The asset the prior call was about.")
    action: Literal["reduce", "increase", "hold"] = Field(
        description="The action the prior report recommended."
    )
    recommended_at: str = Field(
        description="ISO date of the report that made the call."
    )
    pct_move_since: float | None = Field(
        default=None,
        description="Percent price move since the call; None if not retrievable.",
    )
    grade: Literal["good", "poor", "neutral", "insufficient_data"] = Field(
        description="good = the call aged well, poor = it didn't, neutral = a hold that moved, insufficient_data = no price history."
    )


class AdviceReview(BaseModel):
    """Backward-looking report card on the previous report's calls (V13).

    Computed deterministically at the boundary by comparing each prior
    recommendation's asset price then vs now — no LLM. One-step look-back only.
    """

    recommended_at: str | None = Field(
        default=None, description="ISO date of the prior report, or None if none."
    )
    calls: List[GradedCall] = Field(default_factory=list)
    summary: str = Field(
        default="", description="One-line tally, e.g. '2 good · 1 poor'."
    )


class AskRequest(BaseModel):
    """Body for POST /api/reports/{report_id}/ask — a grounded follow-up (V14)."""

    question: str = Field(
        min_length=1, description="The user's question about this report."
    )
